### ISSUE TITLE
Assertion failed: ps->server_grabbed

### ISSUE THREAD

**Issue by apprehensions** [allusive-dev/picom-allusive#29] opened 2023-11-10 18:19 UTC
<-- Please fill in all the forms below that are relevant then delete this line -->

**What is the issue**
Assertion failure within this project

**What did you expect**
Program runs

**Relevant Images or Videos:**
```
Assertion failed: ps->server_grabbed (../src/c2.c: c2_match: 1671)
Aborted
```

**Your configuration**
Default, no configuration file is present

**Package Version:** f796e60a0bafd10e7a956e6c791b2198e7f06141
**Build Method:** Source (`meson setup -Dregex=false build`)
**WM:** dwm

Original picom runs fine.

**Comment by allusive-dev** [comment] 2023-11-10 20:49
@apprehensions 
You may not have all the required [dependencies](https://github.com/allusive-dev/picom-allusive#building-manually).
I ran the same command as you and their were no issues.

**Comment by apprehensions** [comment] 2023-11-10 21:05
PCRE is not a official dependency. it is optional. Please update your README to reflect that.

Why is PCRE required for this though? Regular picom functions fine without it.

**Comment by allusive-dev** [comment] 2023-11-10 21:08
> PCRE is not a official dependency. it is optional.

It is actually. Look at [picom-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=picom-git)

**Comment by allusive-dev** [comment] 2023-11-10 21:16
Either way I can confirm PCRE is required for this fork of picom to my knowledge.

**Comment by apprehensions** [comment] 2023-11-10 21:23
No. It is a OPTIONAL dependency.

https://github.com/allusive-dev/picom-allusive/blob/f796e60a0bafd10e7a956e6c791b2198e7f06141/src/meson.build#L46

It can be disabled.

**Comment by allusive-dev** [comment] 2023-11-10 21:25
> If you truly believe it is required then make it a forced dependency with no options.

I'll do that in a second then.
Can you please try building with PCRE installed.

**Comment by apprehensions** [comment] 2023-11-11 06:21
https://github.com/yshui/picom/commit/e2b8c3fd1e5eb06c137daf03dcb6c11f93aa2cd4
PCRE is deprecated. USE PCRE2, or just update this fork...

**Comment by apprehensions** [comment] 2023-11-11 06:24
Building with PCRE does not help:
```
Assertion failed: ps->server_grabbed (../src/c2.c: c2_match: 1672)
Aborted
```

`c2` is the original file for regex (which if you went through the source code to begin with, you would have known). Please update your fork and fix this issue

**Comment by allusive-dev** [comment] 2023-11-11 06:32
I would appreciate you be a bit more courteous with your wording.

> (which if you went through the source code to begin with, you would have known)
Please don't insinuate that I am now putting effort into this project, I'm trying very hard to fix all the issues people have had with picom and make it better.

I will make the updates however in the future please consider the choosing of your words more carefully.

**Comment by apprehensions** [comment] 2023-11-11 06:34
Sorry!

**Comment by allusive-dev** [comment] 2023-11-11 07:36
I'm testing the updates now but it might take quite a while since I need to change the dependencies on NixOS for me to be able to build the package.

When you see `1.5.0` release that will be the patched update.

**Comment by allusive-dev** [comment] 2023-11-12 21:40
@apprehensions 
`1.5.0` has released with the updated dependency.

**Closed** 2023-11-13 07:23 UTC
Labels: in progress
