### ISSUE TITLE
Rounded corners are black on most windows (i3)

### ISSUE THREAD

**Issue by nousername33** [allusive-dev/picom-allusive#18] opened 2023-11-02 20:05 UTC
On some windows, the rounded corners work perfectly. However, most windows (kitty, electron-based, gtk, qt, etc...) have rounded corners that are filled in. Note that changing detect-rounded-corners does not fix it.

**Comment by nousername33** [comment] 2023-11-02 20:06
I am using standard i3 with no patches.

**Comment by allusive-dev** [comment] 2023-11-02 20:24
Hello @nousername33 
What version of the package are you using and how do you install it?

**Comment by nousername33** [comment] 2023-11-02 21:43
Hi, thanks for answering so quickly! I am using 1.2.3-1 and I got it from the AUR.

**Comment by allusive-dev** [comment] 2023-11-02 22:05
Ok. I have a guess what the issue is. 
`v1.2.3` fixed an issue on AwesomeWM where rounded corners were rendering oddly.
When I first tested the update I guessed it might break other WM's but after testing it on XMonad and it not breaking I thought it was fine.

If you can manually build picom, can you please try removing `1.2.3` and manually building `1.2.2`
https://github.com/allusive-dev/picom-allusive/releases/tag/1.2.2

**Comment by allusive-dev** [comment] 2023-11-02 23:08
Forget what I just sent.
Update to `1.2.4` @nousername33 
Should hopefully fix the issue.

**Comment by nousername33** [comment] 2023-11-03 13:29
Unfortunately it did not.

**Comment by allusive-dev** [comment] 2023-11-03 20:27
> Unfortunately it did not.

@nousername33 Can you send images or videos of the issue?
Also after what update did the issue start occuring?

**Comment by amkillam** [comment] 2023-11-03 20:47
Experiencing this issue in bspwm as well.

![image](https://github.com/allusive-dev/picom-allusive/assets/116528597/51d50f9b-b48b-47c0-b3f5-2034cbdc25e4)

**Comment by amkillam** [comment] 2023-11-03 20:49
Only installed this last night, so unsure when it started. Otherwise, really awesome fork! Picom animations are super smooth.

**Comment by allusive-dev** [comment] 2023-11-03 20:51
This issue is related to [yshui/picom-#808](https://github.com/yshui/picom/issues/808)

**Comment by allusive-dev** [comment] 2023-11-03 20:51
I'll start work on this soon and come back with a release.

**Comment by amkillam** [comment] 2023-11-03 20:52
@allusive-dev if it helps, I had this occur in every other picom fork as well, except for picom-ibhagwan, which was recently removed from the aur, hence the switch lol.

**Comment by allusive-dev** [comment] 2023-11-03 20:53
> @allusive-dev if it helps, I had this occur in every other picom fork as well, except for picom-ibhagwan, which was recently removed from the aur, hence the switch lol.

Makes sense because the PR that was supposed to fix the issue was never merged into `yshui/picom` lol

**Comment by amkillam** [comment] 2023-11-03 20:55
> > @allusive-dev if it helps, I had this occur in every other picom fork as well, except for picom-ibhagwan, which was recently removed from the aur, hence the switch lol.
> 
> Makes sense because the PR that was supposed to fix the issue was never merged into `yshui/picom` lol

Ah that makes a lot of sense lol. 

https://github.com/yshui/picom/commit/60eb00ce1b52aee46d343481d0530d5013ab850b

Here's the diff of the changes in that branch

**Comment by allusive-dev** [comment] 2023-11-03 21:13
@nousername33 @amkillam

I am releasing update `1.2.9`, please let me know if it resolves the issues.

**Comment by amkillam** [comment] 2023-11-04 00:45
@allusive-dev Unfortunately the issue is still present, though I appreciate and am impressed by your very fast response time!

**Comment by allusive-dev** [comment] 2023-11-04 01:59
@nousername33
I just installed `i3` and tested with `1.2.9` and there are no issues with black corners anymore. I tested with kitty as you said it was affected but it is not now.

**Comment by allusive-dev** [comment] 2023-11-04 02:00
@amkillam I am going to install `bspwm` and test on there now.

**Comment by allusive-dev** [comment] 2023-11-04 03:51
@amkillam 

I just got `bspwm` setup. And ran picom with my config and there is absolutely no issues with picom.

The last thing I can assume is this is either a hardware issue or a problem with your configuration.

I will attach my configuration, please use it and let me know if the issue is still present.

**Comment by amkillam** [comment] 2023-11-04 16:54
@allusive-dev  I just switched to linux-git, for unrelated reasons. Inexplicably, the corners are now working! I'm unsure why they're working now despite quite a few reboots with them not working since the changes you pushed, but I'm content regardless lol. Good work! All seems to be working perfectly now.

**Comment by amkillam** [comment] 2023-11-04 17:26
@allusive-dev  I just switched to linux-git, for unrelated reasons. Inexplicably, the corners are now working! I'm unsure why they're working now despite quite a few reboots with them not working since the changes you pushed, but I'm content regardless lol. Good work! All seems to be working perfectly now.

**Comment by allusive-dev** [comment] 2023-11-04 20:30
> @allusive-dev I just switched to linux-git, for unrelated reasons. Inexplicably, the corners are now working! I'm unsure why they're working now despite quite a few reboots with them not working since the changes you pushed, but I'm content regardless lol. Good work! All seems to be working perfectly now.

I'm very happy to hear that it is working for you. Please make sure to let me know if anything else comes up.

@nousername33 I am going to close this issue now under the assumption the issue is solved since I tested it.
If this is not the case please feel free to comment again on here and I will re-open it.

**Closed by allusive-dev** 2023-11-04 20:30 UTC
Labels: bug, in progress, wm-specific
